SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


-- MySQL Script generated by MySQL Workbench
-- Tue Jul 18 16:58:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema panier_local
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `panier_local` ;

-- -----------------------------------------------------
-- Schema panier_local
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `panier_local` DEFAULT CHARACTER SET utf8 ;
USE `panier_local` ;

-- -----------------------------------------------------
-- Table `panier_local`.`command`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `panier_local`.`command` ;

CREATE TABLE IF NOT EXISTS `panier_local`.`command` (
  `ID` VARCHAR(255) NOT NULL,
  `userID` INT NULL,
  `deleted_user_firstname` VARCHAR(80) NULL DEFAULT NULL,
  `deleted_user_lastname` VARCHAR(80) NULL DEFAULT NULL,
  `producerID` INT NULL,
  `deleted_producer_firstname` VARCHAR(80) NULL DEFAULT NULL,
  `deleted_producer_lastname` VARCHAR(80) NULL DEFAULT NULL,
  `date` DATE NOT NULL,
  `status` ENUM("Requested", "In process", "Ready for pick up", "Done", "Cancelled") NOT NULL DEFAULT '\"Requested\"',
  PRIMARY KEY (`ID`),
  INDEX `fk_commande_utilisateur1_idx` (`userID` ASC) VISIBLE,
  INDEX `fk_commande_producteur1_idx` (`producerID` ASC) VISIBLE,
  CONSTRAINT `fk_commande_utilisateur1`
    FOREIGN KEY (`userID`)
    REFERENCES `panier_local`.`user` (`ID`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_producteur1`
    FOREIGN KEY (`producerID`)
    REFERENCES `panier_local`.`producer` (`producerID`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panier_local`.`commandElement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `panier_local`.`commandElement` ;

CREATE TABLE IF NOT EXISTS `panier_local`.`commandElement` (
  `ID` VARCHAR(255) NOT NULL,
  `commandeID` VARCHAR(255) NOT NULL,
  `productName` VARCHAR(80) NOT NULL,
  `productPrice` FLOAT NOT NULL,
  `productQuantity` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_command_commandElement`
    FOREIGN KEY (`ID`)
    REFERENCES `panier_local`.`command` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panier_local`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `panier_local`.`department` ;

CREATE TABLE IF NOT EXISTS `panier_local`.`department` (
  `ID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panier_local`.`producer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `panier_local`.`producer` ;

CREATE TABLE IF NOT EXISTS `panier_local`.`producer` (
  `producerID` INT NOT NULL,
  `isSelling` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`producerID`),
  CONSTRAINT `fk_producteur_utilisateur1`
    FOREIGN KEY (`producerID`)
    REFERENCES `panier_local`.`user` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panier_local`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `panier_local`.`product` ;

CREATE TABLE IF NOT EXISTS `panier_local`.`product` (
  `ID` INT NOT NULL,
  `productInfoID` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `quantity` ENUM("unitaire", "kg", "g") NOT NULL DEFAULT '\"kg\"',
  PRIMARY KEY (`ID`),
  INDEX `fk_produit_productInfo1_idx` (`productInfoID` ASC) VISIBLE,
  CONSTRAINT `fk_product_productInfo`
    FOREIGN KEY (`productInfoID`)
    REFERENCES `panier_local`.`productInfo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_producer`
    FOREIGN KEY (`ID`)
    REFERENCES `panier_local`.`producer` (`producerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panier_local`.`productInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `panier_local`.`productInfo` ;

CREATE TABLE IF NOT EXISTS `panier_local`.`productInfo` (
  `ID` INT NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panier_local`.`region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `panier_local`.`region` ;

CREATE TABLE IF NOT EXISTS `panier_local`.`region` (
  `ID` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `panier_local`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `panier_local`.`user` ;

CREATE TABLE IF NOT EXISTS `panier_local`.`user` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(80) NOT NULL,
  `lastname` VARCHAR(80) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(20) NULL,
  `password` VARCHAR(255) NOT NULL,
  `regionID` INT NULL,
  `departmentID` INT NULL,
  `ville` VARCHAR(80) NOT NULL,
  `addresse` VARCHAR(255) NOT NULL,
  `role` ENUM("client", "producteur") NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_utilisateur_région1_idx` (`regionID` ASC) VISIBLE,
  INDEX `fk_utilisateur_département1_idx` (`departmentID` ASC) VISIBLE,
  CONSTRAINT `fk_utilisateur_région1`
    FOREIGN KEY (`regionID`)
    REFERENCES `panier_local`.`region` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_département1`
    FOREIGN KEY (`departmentID`)
    REFERENCES `panier_local`.`department` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

